services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: cardiohubdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_NAME: cardiohubdb
      DB_USER: devuser
      DB_PASSWORD: devpassword
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: ton_secret_key
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

volumes:
  db_data:
